#!/usr/bin/env python3
"""Mechanical conformance scanner for roaster verification.

Extracts EVIDENCE (matching lines) for each rule from the saved verbatim
reviewer prompts and the final artifacts. Does not make final pass/fail
calls on judgment items — it surfaces candidate violations for human review.
"""
import re
from pathlib import Path

ROOT = Path("/Users/rd/devel/PE_Library/__SKILLS__/roaster-workspace/iteration-1")

EVALS = {
    "eval-0-content-observability": {
        "artifact": "observability-post.md",
        "brief_substr": "draft LinkedIn post i wrote about observability",
        "pt_expected": "PRESENT",
    },
    "eval-1-code-parse-range": {
        "artifact": "parse_range.py",
        "brief_substr": "review and harden this parse_range function",
        "pt_expected": "ABSENT",
    },
    "eval-2-plan-redis-migration": {
        "artifact": "redis-migration-plan.md",
        "brief_substr": "move user sessions from postgres to redis",
        "pt_expected": "OPTIONAL",
    },
}

# (label, regex, kind)  kind: 'forbidden' (want 0 hits) or 'required' (want >=1)
PROMPT_CHECKS = [
    ("ROLE_ASSIGNMENT", r"(?i)\b(you are|you're|act as|take the role|your role is|assume the role|you will (?:act|serve|play|be)|as (?:the|a) (?:defender|reviewer|auditor|critic|expert)|in your role)\b", "forbidden"),
    ("PERSONA_TITLE_CAPS", r"\b(DEFENDER|AUDITOR|CRITIC|REVIEWER|EXPERT)\b", "forbidden"),
    ("META_JARGON", r"(?i)\b(blind[\s-]?attack|hostile critic|adversarial|self[\s-]?refine|refinement loop|\biteration\b|\bpipeline\b|round\s*\d|capitulat|converge|\bDEFENDER\b|fixed[\s-]point|person triangulation)\b", "forbidden"),
    ("SPEC_CATEGORY_LABELS", r"(?i)(\bmission\b\s*:|\bgoals?\b\s*:|\bpremises?\b\s*:|\bconstraints?\b\s*:|anti[\s-]?requirement|\bhard constraint\b|\bsoft constraint\b)", "forbidden"),
    ("SPEC_IDS", r"\b([GP]\d+|CH\d+|CS\d+|AR\d+)\b", "forbidden"),
    ("TASK_ASSIGNMENT", r"(?i)(either revise|revise the artifact|fix (?:this|the|each|it)|defend or revise|if (?:it'?s )?real.*fix|apply (?:the )?fix|edit the artifact|produce (?:either )?a revised|do not (?:ask|negotiate))", "forbidden"),
    ("DECLARATIVE_DISTRUST_OPENER", r"(?i)(don'?t trust|do not trust|i distrust|needs (?:rigorous )?verification|cannot be trusted)", "required"),
    ("SYMMETRIC_DISTRUST", r"(?i)(don'?t assume the concerns|concerns? (?:are|is) right either|assume (?:neither|the concerns)|nor that the concerns)", "required"),
    ("PEER_TRUST", r"(?i)(relying on (?:your|you)|i'?m relying|counting on your|trust your (?:research|inspection|judgment))", "required"),
    ("PT_ATTRIBUTION", r"(?i)(chatgpt|ai slop|linkedin[\s-]?slop|junior (?:model|agent|contributor)|naively|generated by (?:a|an)|autocomplete|copilot|free[\s-]?tier|low[\s-]?effort|early[\s-]?generation|cheap .*(?:model|output)|flagged for quality|legacy (?:tool|pipeline)|without (?:testing|review|thinking)|inexperienced)", "info"),
]

ARTIFACT_CHECKS = [
    ("OUTPUT_HYGIENE", r"(?i)\b(roaster|roast|blind[\s-]?attack|DEFENDER|capitulat|\bconverge\b|self[\s-]?refine|person triangulation|sub[\s-]?agent|reviewer pass|defense signal|master classif)\b", "forbidden"),
]


def scan(text, regex):
    out = []
    for i, line in enumerate(text.splitlines(), 1):
        for m in re.finditer(regex, line):
            out.append((i, m.group(0), line.strip()[:140]))
    return out


for ev, cfg in EVALS.items():
    print("\n" + "=" * 78)
    print(f"EVAL: {ev}   (PT expected: {cfg['pt_expected']})")
    print("=" * 78)
    base = ROOT / ev / "with_skill" / "run-1" / "outputs"

    prompts = sorted(base.glob("reviewer_prompt_round_*.txt"))
    print(f"\n  reviewer prompts found: {[p.name for p in prompts]}")
    for p in prompts:
        text = p.read_text()
        # brief verbatim
        has_brief = cfg["brief_substr"] in text.lower()
        print(f"\n  --- {p.name}  (BRIEF_VERBATIM substring present: {has_brief}) ---")
        for label, rgx, kind in PROMPT_CHECKS:
            hits = scan(text, rgx)
            flag = ""
            if kind == "forbidden":
                flag = "  ⚠ VIOLATION?" if hits else "  ok(0)"
            elif kind == "required":
                flag = "  ok(>=1)" if hits else "  ⚠ MISSING"
            else:
                flag = f"  ({len(hits)} hits)"
            print(f"      [{kind:9}] {label:28} {len(hits):2d} hits{flag}")
            for ln, frag, ctx in hits[:4]:
                print(f"            L{ln}: «{frag}»  | {ctx}")

    # artifact hygiene
    art = base / cfg["artifact"]
    if art.exists():
        text = art.read_text()
        print(f"\n  --- FINAL ARTIFACT: {cfg['artifact']} ---")
        for label, rgx, kind in ARTIFACT_CHECKS:
            hits = scan(text, rgx)
            flag = "  ⚠ LEAK?" if hits else "  ok(clean)"
            print(f"      [{label}] {len(hits)} hits{flag}")
            for ln, frag, ctx in hits[:6]:
                print(f"            L{ln}: «{frag}»  | {ctx}")
    else:
        print(f"  !! MISSING ARTIFACT {art}")

print("\n\nDONE — these are CANDIDATE flags; human judges true violations vs false positives.")
