#!/usr/bin/env python3
"""Emit grading.json for each run from explicit per-expectation verdicts.

Verdicts are the human adjudication after reading the saved verbatim prompts,
traces, specs, AR prompts, and final artifacts plus the mechanical scanner.
Loads canonical expectation texts from each eval_metadata.json so text matches
exactly what the viewer shows.
"""
import json
from pathlib import Path

ROOT = Path("/Users/rd/devel/PE_Library/__SKILLS__/roaster-workspace/iteration-1")

P = "Baseline ran no roaster process (no skill loaded): no spec, anti-requirements, reviewer prompt, or trace exists, so this conformance property is not exhibited."

VERDICTS = {
 ("eval-0-content-observability", "with_skill"): [
  (True,  "spec.md: Mission + 4 Goals + 4 Premises + 3 hard + 4 soft constraints; trace Step 1 shows inline enumeration done before any attack."),
  (True,  "ar_inferrer_prompt.txt contains ONLY the requirements (no user history/authoring context); ar_list.md has 13 ARs; trace confirms an isolated sub-agent spawned before Step 2."),
  (True,  "Scanner 0 role hits in both reviewer prompts; openers are 'I don't trust this artifact…' with no 'You are/Act as' and no DEFENDER/REVIEWER/AUDITOR/EXPERT persona."),
  (True,  "Scanner 0 meta hits; no blind-attack/adversarial/self-refine/loop/round-N/capitulate/converge/DEFENDER terms."),
  (True,  "Scanner 0 spec-leak hits; no Mission/Goals/Premises/Constraints labels and no G#/P#/CH#/CS#/AR# IDs in either reviewer prompt."),
  (True,  "The 12 concerns are direct factual claims about the post (e.g. concern 5: 'The claim 87%… is a fabricated, unsourced statistic'); no spec references or category labels."),
  (True,  "reviewer_prompt_round_1.txt L30 pastes the brief verbatim under 'ORIGINAL USER REQUEST (verbatim)': \"Here's a draft LinkedIn post I wrote about observability. Make it solid before I publish it.\""),
  (True,  "Opener 'I don't trust this artifact. It needs rigorous verification.' stops at 'verification' — no appended goal-phrase, no softening clause, no question."),
  (True,  "Closing requests investigation only ('These concerns need rigorous investigation… verify each one'); no fix/edit/defend-or-revise directive (scanner 0 hits)."),
  (True,  "'Don't assume the source got anything right. Don't assume the concerns are right either. Investigate.' present in both rounds."),
  (True,  "Both reviewer prompts end 'Do not edit, create, or overwrite any files; return your analysis as text only.' Trace: reviewer returned text only; MASTER sole writer; original input md5 unchanged."),
  (True,  "trace.md: R1 CAPITULATE (all 12 concerns upheld via deep-research → full rebuild), R2 DEFENSE (new statistic + definition verified against primary sources), DEFENSE-verified vs private spec → STOP."),
  (True,  "Scanner 0 hits on final observability-post.md; no roaster/blind-attack/DEFENDER/capitulate/converge/self-refine/sub-agent vocabulary."),
  (True,  "reviewer_prompt_round_1.txt L3: 'generated by an early-generation ChatGPT-style assistant… the kind of LinkedIn-slop' — scathing source attribution present (required for a content artifact)."),
  (True,  "Final post removes the fabricated 87% stat; replaces the fluff opener with a concrete checkout-incident hook; states the real monitoring-vs-observability mechanism with a concrete debugging example; cites a correctly-sourced, caveated New Relic 2025 figure (23% vs 40%)."),
 ],
 ("eval-0-content-observability", "without_skill"): [
  (False, P)] * 13 + [
  (False, "No reviewer prompt exists (baseline); Person Triangulation is a property of the roaster reviewer prompt, not produced here."),
  (True,  "Baseline rewrite is strong: removes the fabrication (drops invented stats entirely), strips the buzzwords, replaces the fluff opener, adds a concrete region/provider/deploy debugging scenario, an honest cost note, and a genuine closing question. Comparable quality to with_skill, though with no sourced statistic."),
 ],
 ("eval-1-code-parse-range", "with_skill"): [
  (True,  "spec.md: Mission + G1–G5 + P1–P4 + CH1–CH5 + CS1–CS4; trace Step 1 grounded the spec by executing the original (surfaced the off-by-one and silent empties)."),
  (True,  "ar_inferrer_prompt.txt is requirements-only; ar_list.md has 15 ARs; trace records the isolated sub-agent agentId and the Pipeline Completeness Gate before Step 2."),
  (True,  "Scanner 0 role hits both rounds; openers 'I don't trust this code…' carry no persona/role."),
  (True,  "The only scanner 'pipeline' hit is 'came out of a CI pipeline that doesn't validate' — a source-attribution line, NOT a meta-architecture leak. No loop/round/self-refine/DEFENDER."),
  (True,  "Scanner 0 spec-leak hits; concerns carry no Mission/Goal labels or G#/CH# IDs."),
  (True,  "12 (R1) / 11 (R2) concerns are direct claims about the code (e.g. 'parse_range(\"1-5\") returns [1,2,3,4], not [1,2,3,4,5]')."),
  (True,  "Both prompts paste the brief verbatim under the neutral label: 'Review and harden this parse_range function — we use it to parse CLI range args like \\'1-5\\'.'"),
  (True,  "'I don't trust this code. It needs rigorous verification.' — clean opener, no appended goal/softening/question."),
  (True,  "Closing is investigation-only; the 'if a revised version is warranted, include it inline as text' matches the skill's read-only 'returns… a proposed revision as text only' allowance, not an outcome directive (scanner 0 task-assignment hits)."),
  (True,  "'Don't assume the source got anything right. Don't assume the concerns are right either.' present in both rounds."),
  (True,  "Read-only instruction in both prompts; trace: reviewer returned text only, MASTER overwrote the working copy; original parse_range.py md5 329558b4… unchanged."),
  (True,  "trace: R1 CAPITULATE (11/12 confirmed → full rewrite), R2 DEFENSE — reviewer refuted 7/11 and MASTER independently re-ran the load-bearing refutations (DoS guard peak 1278 B; Unicode digits rejected; ValueError subclass still caught) → STOP."),
  (True,  "Scanner 0 hits on final parse_range.py; docstring/comments describe only the contract and behavior."),
  (False, "SKILL CONTRADICTION (not an execution error). Source attribution was used on this CODE artifact in both rounds ('basic copilot-style autocomplete without testing'; 'CI pipeline that doesn't validate'). The skill says 'skip Person Triangulation on code', yet templates.md EQUATES PT with the mandatory opener source-attribution and supplies code-specific variants — so 'skip PT on code' is unsatisfiable as written. The runner's reading (skip the appended PT tail-line, keep the source-attribution opener) is defensible; this FAIL flags the skill defect."),
  (True,  "Off-by-one fixed (range(start, end+1); '1-5'→[1,2,3,4,5], verified in the trace matrix); RangeParseError(ValueError) with input-naming messages; regex validation incl. ASCII-only [0-9]; MAX_RANGE_SIZE DoS guard; docstring + type hints; descending rejected; __main__ exercises error paths."),
 ],
 ("eval-1-code-parse-range", "without_skill"): [
  (False, P)] * 13 + [
  (False, "No reviewer prompt exists (baseline); PT-skip is a property of the roaster reviewer prompt, not produced here. (The baseline trivially used no attribution, but the conformance property is not exhibited.)"),
  (True,  "Baseline code is also strong: off-by-one fixed, RangeParseError, regex validation, MAX_RANGE_SIZE guard, docstring, type hints, and a 19-case self-test suite (per summary). Marginally less robust than with_skill (uses Unicode-aware \\d rather than ASCII [0-9]; __main__ prints rather than asserts), but a solid one-pass hardening."),
 ],
 ("eval-2-plan-redis-migration", "with_skill"): [
  (True,  "spec.md: Mission + 5 Goals + 5 Premises + 4 hard + 4 soft constraints; trace Step 1 inline enumeration before any attack."),
  (True,  "ar_inferrer_prompt.txt is requirements-only; ar_list.md has 15 ARs (flagged asymmetric-rollback + backfill write-gap as highest-severity); isolated sub-agent before Step 2."),
  (True,  "Scanner 0 role hits both rounds; 'I don't trust this artifact…' no persona."),
  (True,  "Scanner 0 meta hits; no loop/round/blind-attack/self-refine/DEFENDER."),
  (True,  "Scanner 0 spec-leak hits; no Mission/Goals/Constraints labels or IDs."),
  (True,  "15 (R1) concerns are direct claims about the plan (e.g. 'Standing up a single Redis instance makes the authentication system strictly less reliable than the Postgres it replaces')."),
  (True,  "Brief pasted verbatim: 'Here's our plan to move user sessions from Postgres to Redis. Review it before we run it this Saturday.'"),
  (True,  "'I don't trust this artifact. It needs rigorous verification.' — clean opener, no appended goal/softening/question."),
  (True,  "Investigation-only closing; scanner 0 task-assignment hits."),
  (True,  "'Don't assume the source got anything right. Don't assume the concerns are right either.' present both rounds."),
  (True,  "Read-only instruction present; trace: reviewer text-only, MASTER sole writer authored s1/s2; original plan untouched."),
  (True,  "trace: R1 CAPITULATE (13/15 confirmed → full expand/contract rewrite), R2 CONVERGE/DEFENSE — core design defended with primary sources; 5 corrections accepted, including fixing a false 'volatile-ttl spares valid sessions' claim MASTER itself introduced in s1 → STOP. Compact notation used."),
  (True,  "Final plan output-hygiene: only 'defense' as an ordinary domain word ('primary defense against a serialization bug'); no roaster/blind-attack/DEFENDER/capitulate/converge/sub-agent."),
  (True,  "Immediate 'drop sessions table' removed from the cutover window; the table is retained through a soak and dropped only later as a separate scheduled change; explicit rollback path + named rollback decision-owner + hard abort criteria added."),
  (True,  "Big-bang cutover replaced with expand/contract: dual-write → backfill with TTL preservation (PTTL→RESTORE) → shadow-read compare → staged 1→10→50→100% rollout → multi-day soak; HA Redis (primary/replica + failover) + durability (AOF/everysec/WAIT/min-replicas); monitoring/alerting + objective baselined go/no-go gates; schedule note that 'this Saturday' is not safely achievable."),
 ],
 ("eval-2-plan-redis-migration", "without_skill"): [
  (False, P)] * 13 + [
  (False, "Baseline did NOT produce a revised plan — it preserved the original 4-step plan verbatim and APPENDED a review. The destructive Step 4 (drop sessions table) and single-Redis SPOF remain the operative 'plan' in the deliverable, so the artifact is not a safe runnable plan. (The appended review IS high quality and correctly recommends removing Step 4 + a rollback — credited qualitatively, but the artifact itself was not made safe.)"),
  (False, "Same: the appended review recommends dual-write / staged rollout / monitoring / HA, but the plan body still says switch-to-Redis + deploy-to-all-servers-at-once with no migration of existing sessions. No revised, runnable plan was produced — executing 'the plan' in the file still runs the unsafe steps."),
 ],
}

for (ev, cfg), verdicts in VERDICTS.items():
    meta = json.loads((ROOT / ev / "eval_metadata.json").read_text())
    texts = meta["expectations"]
    assert len(texts) == len(verdicts) == 15, f"{ev}/{cfg}: {len(texts)} texts vs {len(verdicts)} verdicts"
    exps = [{"text": t, "passed": bool(p), "evidence": e} for t, (p, e) in zip(texts, verdicts)]
    passed = sum(1 for x in exps if x["passed"])
    total = len(exps)
    grading = {
        "expectations": exps,
        "summary": {
            "passed": passed,
            "failed": total - passed,
            "total": total,
            "pass_rate": round(passed / total, 4),
        },
    }
    out = ROOT / ev / cfg / "run-1" / "grading.json"
    out.write_text(json.dumps(grading, indent=2) + "\n")
    print(f"{ev}/{cfg}: {passed}/{total} = {passed/total:.2%}  -> {out}")
