#!/usr/bin/env python3
import json
from pathlib import Path

bench = Path("/Users/rd/devel/PE_Library/__SKILLS__/roaster-workspace/iteration-1/benchmark.json")
data = json.loads(bench.read_text())
data["metadata"]["executor_model"] = "claude-opus-4-8[1m] (runners) / inline MASTER"
data["metadata"]["runs_per_configuration"] = 1
data["notes"] = [
 "PASS-RATE = CONFORMANCE, not artifact quality. 13 of 15 expectations check whether roaster executed its own MUST/MUST-NOT rules (spec built, AR isolated, no role/meta/spec-leak in reviewer prompts, read-only discipline, output hygiene, MASTER classification). The baseline runs no roaster process, so its ~0-7% is BY CONSTRUCTION and does NOT mean baseline outputs are poor. Read the 98% as 'the skill executed its specified architecture correctly'.",
 "The ONE with_skill failure (eval-1 PT_ABSENT) is a SKILL DEFECT, not an execution error. The skill says 'skip Person Triangulation on code', but templates.md EQUATES PT with the mandatory opener source-attribution AND supplies code-specific variants -> 'skip PT on code' is unsatisfiable as written. The code runner used a code source-attribution opener (defensible). FIX: disambiguate 'opener source-attribution (always, domain-appropriate)' from 'appended PT pressure line (skip on code)', or drop the skip-on-code rule.",
 "Two further internal contradictions were found that did NOT manifest (runners followed the canonical template) but are latent landmines: (a) the 'Prompt Framing' section + templates.md forbid ANY role including 'reviewer', yet Step 3 and the Anti-Patterns say 'Cast as senior REVIEWER'; (b) templates.md 'Attack Template - Mechanical Fill' still carries an explicit task assignment ('Either revise... OR explain... Produce either a revised artifact or a point-by-point rebuttal. Do not ask questions.') plus a 'CRITICISM:' label, contradicting the dominant 'pure research request, no task assignment' template. Looks like v3->v4 migration cruft; reconcile or delete the stale sections.",
 "COST is material: with_skill averaged 1322s (~22 min) and ~102k tokens vs baseline 77s / ~22k tokens -- ~17x wall-clock and ~4.6x tokens, driven by real isolated sub-agents (AR-inferrer + 2 reviewer rounds, several doing live web research). Consistent with the skill's own 'When NOT to use: token budgets too tight for >=2 rounds'. Reserve for high-stakes artifacts.",
 "Artifact QUALITY (assessed separately from conformance) varied by task. PLAN: with_skill clearly superior -- it produced a transformed, runnable expand/contract plan, while the baseline left the original destructive plan in place and only APPENDED a critique (executing 'the plan' in the baseline file still runs the unsafe steps). CONTENT: with_skill modestly better (a correctly-sourced, caveated statistic + stronger narrative vs a solid but stat-free baseline). CODE: baseline nearly EQUAL (both fix the off-by-one and harden; with_skill only marginally more robust). Net: the skill's value-add scales with artifact stakes/complexity and is small on simple, well-bounded artifacts.",
 "All three with_skill runs executed with REAL isolated sub-agents (STATEFUL or STATELESS; none DEGRADED) -- the multi-agent blind-attack architecture itself was exercised, not merely the INLINE fallback. Each ran 2 rounds and terminated on a verified DEFENSE/CONVERGE signal. Notably eval-2's round-2 reviewer caught and corrected a factual error MASTER had introduced in its own s1 (a false 'volatile-ttl spares valid sessions' claim) -- evidence the loop corrects the orchestrator, not just the artifact.",
 "METHODOLOGY caveat: 1 run per configuration (no within-config repeats), so the 4% with_skill stddev is purely the eval-1 PT contradiction, not a flakiness measurement. For a robustness/variance read, re-run with 2-3 runs per config. Grading combined a mechanical scanner (role/meta/spec-leak/hygiene greps over the saved verbatim prompts) with human adjudication of the judgment items (concerns-as-direct-assertions, read-only discipline, classification, improvement).",
]
bench.write_text(json.dumps(data, indent=2) + "\n")
print("Injected", len(data["notes"]), "analyst notes into benchmark.json")
for i, n in enumerate(data["notes"], 1):
    print(f"  {i}. {n[:96]}...")
