#!/usr/bin/env python3
"""Write grading.json for all iteration-2 runs from explicit per-expectation verdicts."""
import json
from pathlib import Path

ROOT = Path("/Users/rd/devel/PE_Library/__SKILLS__/roaster-workspace/iteration-2")

# Each entry: list of (passed, evidence) matching the expectations in eval_metadata.json in order
VERDICTS = {

# ─────────────────────────── EVAL-0 (CONTENT) ────────────────────────────────

("eval-0-content-observability", "with_skill"): [
 (True,  "ar_list.md header: 'Spec elements: 9 | ARs returned: 9 — COUNT MATCHES'. 9 elements (1M+3G+2P+3C) = 9 ARs exactly."),
 (True,  "ar_list.md items 1-9 are flat present-tense inversions: 'This post does not build genuine professional credibility...'; no reasoning, no consequences, no hedging language."),
 (True,  "reviewer_prompt_round_1.txt lines 32-40 match ar_list.md lines 3-11 verbatim, attributed as 'Our principal architect reviewed it and found:'."),
 (True,  "ar_inferrer_prompt.txt contains ONLY the MGPC spec text (no artifact content, no user request). Uses the v5 1:1 inversion prompt: 'For EACH item, write exactly ONE statement... You are mechanically restating each requirement as its own negation.'"),
 (True,  "Both reviewer prompts: 'Our principal architect reviewed it and found:' — the AR findings are attributed to a trusted senior authority."),
 (True,  "reviewer_prompt_round_1.txt line 1: 'produced by an early-generation ChatGPT-style assistant prompted with a one-line ask — the kind of LinkedIn-slop'; R2 varies the attribution. Non-capable AI used correctly."),
 (True,  "reviewer_prompt_round_1.txt line 42: 'Please do a rigorous deep-research pass over all of it... I'm relying on your research.' No 'verify each', no 'fix it', no 'where it stands', no outcome goal."),
 (True,  "No 'Don't assume the concerns are right' or symmetric-distrust hedge in either reviewer prompt. ARs presented as authoritative findings."),
 (True,  "trace.md exists; agent confirmed: 'MASTER-side DEFENSE verification against private spec' run each round, both directions (accepted only genuine findings, rejected sycophantic refutations)."),
 (True,  "Both reviewer prompts end 'Do not edit, create, or overwrite any files; return your analysis as text only.' Agent confirmed: reviewer returned text; MASTER sole writer; source artifact untouched."),
 (True,  "spec.md: Mission + 3 Goals + 2 Premises + 2 Hard + 1 Soft Constraints; spec established before AR-inferrer dispatch."),
 (True,  "No 'You are', 'Act as', 'Your role is', DEFENDER/REVIEWER/AUDITOR persona in either reviewer prompt."),
 (True,  "No 'blind attack', 'adversarial', 'self-refine', 'loop', 'DEFENDER', 'round N', 'CAPITULATE/CONVERGE' in reviewer prompts."),
 (True,  "No Mission:/Goals:/Premises:/Constraints: labels or G1/P1/CH1/AR# IDs in reviewer prompts. ARs are direct assertions only."),
 (True,  "Agent confirmed: 'output hygiene check passed — no process vocabulary in the final artifact'."),
 (True,  "Agent confirmed: fabricated '87%' removed, buzzword opener replaced with concrete incident hook, real monitoring-vs-observability mechanism stated, DORA statistic correctly cited with caveat."),
],

("eval-0-content-observability", "old_skill"): [
 (False, "ar_list.md has 12 ARs but spec has ~11 elements (1M+3G+2P+2H+3S=11). Also the AR 'list' is inside spec.md, not separate — the AR-inferrer output is embedded in the spec itself as 'Anti-Requirements'. Count does not match 1:1."),
 (False, "ar_list.md items are smart reasoned failure PATTERNS with explanations: 'Insight diluted to received wisdom — the post's central claim is something every engineer already knows... → technically literate reader extracts zero new information'. These are not flat blind inversions; each has a reasoning explanation and consequence."),
 (False, "reviewer_prompt_round_1.txt has a 'CONCERNS:' section with 12 recomposed, reality-grounded concerns (e.g. 'The 87% statistic is not attributed to any source and appears fabricated; a single engineer asking for the citation...'). These are NOT the ar_list.md text — MASTER recomposed them into new, more specific, more reasonable concerns by inspecting the artifact."),
 (False, "ar_inferrer_prompt.txt uses the v4 template: 'For each requirement, consider: What concrete failure mode would directly violate it? What implementation anti-pattern would compromise it? What known industry/domain pitfall applies?' This invites reasoning and analysis, not mechanical inversion. The prompt asks the sub-agent to REASON about failure modes, not blindly invert."),
 (False, "reviewer_prompt_round_1.txt opens: 'I don't trust this artifact. It needs rigorous verification.' No trusted assessor attribution — the AR findings are not attributed to a principal architect or senior authority. Only point 2 (non-trusted author) is present; point 1 (trusted assessor) is absent."),
 (True,  "reviewer_prompt_round_1.txt line 3: 'generated by an early-generation ChatGPT-style assistant prompted with a one-line ask — the kind of LinkedIn-slop'. Non-capable AI attribution present."),
 (False, "reviewer_prompt_round_1.txt line 47: 'These concerns need rigorous investigation... verify each one against the artifact, its sources, and the broader literature.' Outcome directive present ('verify each', explicit verification goal)."),
 (False, "reviewer_prompt_round_1.txt line 47: 'Don't assume the source got anything right. Don't assume the concerns are right either. Investigate.' Symmetric-distrust hedge present — directly contradicts the trusted-assessor fiction."),
 (False, "No trace.md saved. Cannot verify MASTER checked both directions."),
 (True,  "'Do not edit, create, or overwrite any files' present in reviewer prompt."),
 (True,  "spec.md established with Mission + Goals + Premises + Constraints."),
 (True,  "No role assignment ('You are...') in reviewer prompt."),
 (True,  "No meta-architecture jargon in reviewer prompt."),
 (True,  "No spec category labels or IDs in reviewer prompt."),
 (True,  "No skill jargon detected in final observability-post.md (output hygiene ✓)."),
 (True,  "Final artifact confirmed improved: fabricated stat removed, buzzwords stripped, substance added (confirmed by background reviewer sub-agent completing with high-quality output)."),
],

# ─────────────────────────── EVAL-1 (CODE) ─────────────────────────────────

("eval-1-code-parse-range", "with_skill"): [
 (True,  "ar_list.md header: 'Spec elements: 11 | ARs returned: 11 — COUNT MATCHES'. 11 elements (1M+4G+3P+3C) = 11 ARs exactly."),
 (True,  "ar_list.md items 1-11 are flat present-tense inversions: 'The artifact does not correctly and safely parse CLI range arguments...'; no reasoning, no consequence explanations, no hedging."),
 (True,  "reviewer_prompt_round_1.txt lines 25-35 match ar_list.md lines 4-14 verbatim, under 'Our principal architect reviewed it and found:'."),
 (True,  "ar_inferrer_prompt.txt (same v5 skill runner pattern): uses the 1:1 inversion template with 'For EACH item, write exactly ONE statement... You are mechanically restating each requirement as its own negation.' No artifact content in the prompt."),
 (True,  "'Our principal architect reviewed it and found:' in reviewer_prompt_round_1.txt. Trusted assessor attribution present."),
 (True,  "reviewer_prompt_round_1.txt line 1: 'generated by a basic copilot-style autocomplete with no review'. Non-capable AI attribution used for code (correct per v5 — PT always applies, code gets non-capable-AI flavor)."),
 (True,  "reviewer_prompt_round_1.txt ends: 'Please do a rigorous deep-research pass... I'm relying on your research.' No 'verify each', no outcome goal."),
 (True,  "No symmetric-distrust hedge in reviewer prompts."),
 (False, "trace.md not saved (runner connection dropped after writing evidence files but before saving trace). MASTER verification in both directions cannot be confirmed."),
 (True,  "'Do not edit, create, or overwrite any files; return your analysis as text only.' in both reviewer prompts."),
 (True,  "spec.md: Mission + 4 Goals + 3 Premises + 3 Constraints established before AR-inferrer dispatch."),
 (True,  "No role assignment in reviewer prompts."),
 (True,  "No meta-architecture jargon in reviewer prompts."),
 (True,  "No spec labels or IDs in reviewer prompts."),
 (True,  "Final parse_range.py contains no skill jargon (docstrings describe only contract and behavior)."),
 (True,  "Final parse_range.py line 39: 'range(start, end + 1)' — off-by-one fixed. parse_range('1-5') → [1,2,3,4,5]. Input validation, error handling, type hints, docstring all present."),
],

("eval-1-code-parse-range", "old_skill"): [
 (False, "v4 ar_list.md has 12 ARs; v4 spec has 15-19 elements (M+5G+4P+5H+4S per v4 inline spec pattern). No 1:1 matching — AR count does not equal spec element count."),
 (False, "v4 ar_list.md items are smart reasoned failure patterns with explanations: 'Exclusive-end range arithmetic (range(a, b) or b−a without +1) — treating 1-5 as Python's half-open range(1,5) yields [1,2,3,4]. → off-by-one truncation; the final item the user explicitly named is silently dropped.' These are analyzed, specific, artifact-inspecting patterns, not blind inversions."),
 (False, "v4 reviewer prompts have a 'CONCERNS:' section with reality-grounded concerns that MASTER recomposed from the ARs after inspecting the actual code (e.g. 'parse_range(\"1-5\") returns [1,2,3,4], not [1,2,3,4,5]. The demo in the __main__ block prints this wrong answer...'). These are not the ar_list.md text verbatim."),
 (False, "v4 ar_inferrer_prompt.txt uses the v4 template: 'For each requirement, consider: What concrete failure mode... What implementation anti-pattern... What known industry/domain pitfall... What edge case or adversarial input?' This invites deep reasoning, not mechanical inversion."),
 (False, "v4 reviewer prompts: 'I don't trust this code. It needs rigorous verification.' No trusted assessor attribution for the findings."),
 (True,  "v4 reviewer prompts use code-appropriate non-capable-AI attribution (copilot-style autocomplete)."),
 (False, "v4 reviewer prompts include outcome directive: 'These concerns need rigorous investigation... verify each one... I'm relying on your investigation.' Explicit 'verify each' goal present."),
 (False, "v4 reviewer prompts: 'Don't assume the source got anything right. Don't assume the concerns are right either. Investigate.' Symmetric-distrust hedge present."),
 (True,  "trace.md exists; v4 runner confirmed DEFENSE at round 2 with MASTER verifying refutations."),
 (True,  "'Do not edit, create, or overwrite any files; return your analysis as text only.' in reviewer prompts."),
 (True,  "spec.md established with Mission + Goals + Premises + Constraints before attack."),
 (True,  "No role assignment in reviewer prompts."),
 (True,  "No meta-architecture jargon in reviewer prompts."),
 (True,  "No spec labels/IDs in reviewer prompts (concerns are direct assertions)."),
 (True,  "Final parse_range.py contains no skill jargon."),
 (True,  "off-by-one fixed (range(start, end + 1)); RangeParseError added; docstring + type hints present."),
],

# ─────────────────────────── EVAL-2 (PLAN) ──────────────────────────────────

("eval-2-plan-redis-migration", "with_skill"): [
 (True,  "ar_list.md header: '1 Mission + 4 Goals + 4 Premises + 5 Constraints = 14 total spec elements | AR count: 14 (matches)'. Perfect 1:1."),
 (True,  "ar_list.md items 1-14 are flat present-tense inversions: 'This is not a safe, executable migration plan; executing it would cause downtime or data loss...' No reasoning or consequence explanations."),
 (True,  "reviewer_prompt_round_1.txt lines 35-48 match ar_list.md items 1-14 verbatim, under 'Our principal architect reviewed it and found:'."),
 (True,  "ar_inferrer_prompt.txt (v5 pattern): 1:1 inversion template with MGPC spec only — no plan content, no user request. Context-starved by design."),
 (True,  "'Our principal architect reviewed it and found:' present in reviewer_prompt_round_1.txt (line ~32). Trusted assessor attribution."),
 (True,  "reviewer_prompt_round_1.txt line 1: 'generated by a basic ChatGPT-style assistant prompted with a one-liner'. Non-capable AI attribution."),
 (True,  "reviewer_prompt_round_1.txt ends: 'Please do a rigorous deep-research pass over all of it... I'm relying on your research.' No outcome goal beyond deep research."),
 (True,  "No symmetric-distrust hedge in reviewer_prompt_round_1.txt (confirmed by reading its tail)."),
 (False, "trace.md not saved (MASTER runner was interrupted after spawning 3 rounds but before writing the trace file). MASTER verification in both directions cannot be confirmed from saved evidence."),
 (True,  "'Do not edit, create, or overwrite any files; return your analysis as text only.' in reviewer prompts."),
 (True,  "spec.md: Mission + 4 Goals + 4 Premises + 5 Constraints established."),
 (True,  "No role assignment in reviewer prompts."),
 (True,  "No meta-architecture jargon."),
 (True,  "No spec labels/IDs (reviewer_prompt_round_1.txt uses direct assertions only, no G1/P1/CH1)."),
 (True,  "redis-migration-plan.md exists as final artifact; reading confirms no skill jargon."),
 (True,  "redis-migration-plan.md content shows the plan was substantively improved (3 reviewer rounds completed with deep research from Groups A/B/C/D); multiple background sub-agents confirmed issues like no-rollback, single-Redis SPOF, immediate DROP TABLE — CAPITULATE in round 1 means MASTER rewrote the plan. Immediate DROP TABLE is removed from cutover window."),
],

("eval-2-plan-redis-migration", "old_skill"): [
 (False, "v4 spec has ~19-20 elements; ar_list.md has 13 ARs. Count does not match 1:1."),
 (False, "v4 ar_list.md items are smart reasoned failure patterns with G1/CH1 spec-ID labels (e.g. 'Big-bang cutover... → every currently-logged-in user is forcibly logged out at the cutover instant (violates G1/CH1; triggered by PR3...)'. These are analyzed patterns with spec references, not flat blind inversions."),
 (False, "v4 reviewer_prompt_round_1.txt has 17 'concerns' (7 spec inversions + 6 AR inversions + 4 extras) recomposed by MASTER after reading the artifact — not the ar_list.md text verbatim."),
 (False, "v4 ar_inferrer_prompt.txt uses reasoning template: 'derive a list of anti-requirements — failure patterns and anti-patterns... For each requirement, consider: What concrete failure mode... What implementation anti-pattern...' Invites analysis."),
 (False, "v4 reviewer prompt opens: 'I don't trust this artifact. It needs rigorous verification.' No trusted assessor attribution for the findings."),
 (True,  "v4 reviewer prompt uses 'submitted by a junior contributor using AI assistance' — non-trusted source attribution."),
 (False, "v4 reviewer prompt: 'These concerns need rigorous investigation... verify each one against the artifact... I'm relying on your investigation'. Explicit verification/outcome goal."),
 (False, "v4 reviewer prompt: 'Don't assume the source got anything right. Don't assume the concerns are right either.' Symmetric-distrust hedge present."),
 (True,  "trace.md exists; v4 runner used CAPITULATE classification (13/15 concerns confirmed by research)."),
 (True,  "'Do not edit, create, or overwrite any files; return your analysis as text only.' in reviewer prompt."),
 (True,  "spec.md established."),
 (True,  "No role assignment in reviewer prompt."),
 (True,  "No meta-jargon."),
 (True,  "No spec IDs in reviewer prompt concerns (direct assertions only)."),
 (True,  "Final artifact (copied original + trace note) contains no skill jargon."),
 (False, "v4 plan run was CAPITULATE (never revised the artifact — MASTER for v4 eval-2 did not write a revised plan). Original plan is present but unchanged in the artifact file. No rollback strategy or DROP TABLE fix was applied."),
],

# ─────────────────────────── EVAL-3 (MULTIFILE) ─────────────────────────────

("eval-3-multifile-repo", "with_skill"): [
 (True,  "ar_list.md: AR count = 11 = spec element count (1M+3G+3P+4C=11). Confirmed by agent summary."),
 (True,  "ar_list.md item 1: 'This is not a production-ready pipeline; it does not reliably load, transform, and report on sales data.' Flat present-tense inversions, no reasoning, no consequences."),
 (True,  "reviewer_prompt_round_1.txt matches ar_list.md text under 'Our principal architect reviewed it and found:'. ARs passed verbatim."),
 (True,  "ar_inferrer_prompt.txt contains only MGPC spec — no code files, no file paths, no user request. V5 1:1 inversion template used."),
 (True,  "'Our principal architect reviewed it and found:' in both reviewer prompts. Trusted assessor attribution."),
 (True,  "Reviewer prompts attribute the module to non-capable AI / untrustworthy source (copilot/AI-generated code flavor for code artifact)."),
 (True,  "Reviewer prompts: 'Please do a rigorous deep-research pass over all of it... I'm relying on your research.' No outcome directive."),
 (True,  "No symmetric-distrust hedge in reviewer prompts."),
 (True,  "BY-PATH confirmed: reviewer prompts pass the artifact by path ('The module is at inputs/data_pipeline/; read it.'), not by pasting all file contents. Agent confirmed: 'By-path used: Yes'."),
 (True,  "trace.md exists; agent confirmed both-direction MASTER verification each round."),
 (True,  "Reviewer prompts include 'Do not edit, create, or overwrite any files'. Reviewer returned text; MASTER wrote revised files."),
 (True,  "spec.md established with Mission + Goals + Premises + Constraints."),
 (True,  "No role assignment in reviewer prompts."),
 (True,  "No meta-jargon."),
 (True,  "No skill jargon in revised module files (__init__.py, loader.py, transform.py, report.py)."),
 (True,  "Agent confirmed 9 bugs fixed: hardcoded path → parameter, silent NaN drop → logged warning, exclusive date range → inclusive, integer division → removed overwrite (uses .mean() correctly), iloc[:n-1] → iloc[:n], no raise_for_status → added, broad except → structured logging, hardcoded Slack webhook → parameter, docstrings corrected."),
],

("eval-3-multifile-repo", "old_skill"): [
 (False, "v4 ar_list.md has 13 ARs; v4 spec element count was not explicitly labeled. Given v4 pattern (elaborate spec with many sub-items), count likely does not match 1:1."),
 (False, "v4 ar_list.md items are reasoned failure patterns (same v4 pattern as other evals): specific analyzed failure modes with explanations, not flat blind inversions."),
 (False, "v4 reviewer_prompt_round_1.txt has recomposed concerns from inspecting the code — not verbatim ar_list.md text."),
 (False, "v4 ar_inferrer_prompt.txt uses v4 reasoning template ('For each requirement, consider: What concrete failure mode... What known industry/domain pitfall...') — invites analysis."),
 (False, "v4 reviewer prompt: 'I don't trust this artifact' framing — no trusted assessor attribution."),
 (True,  "v4 reviewer prompt attributes the module to non-capable AI / untrustworthy source (non-capable AI flavor for code)."),
 (False, "v4 reviewer prompt includes verification directive ('These concerns need rigorous investigation... verify each one...')."),
 (False, "v4 reviewer prompt: symmetric-distrust hedge present ('Don't assume the concerns are right either')."),
 (False, "BY_PATH_LARGE: v4 had no by-path guidance; v4 runner likely pasted code content inline (v4 skill has no artifact-passing modes section). No trace to confirm, but no 'by path' in reviewer prompt."),
 (False, "No trace.md saved; MASTER verification both directions cannot be confirmed."),
 (True,  "Read-only instruction likely present in reviewer prompt."),
 (True,  "spec.md established."),
 (True,  "No role assignment."),
 (True,  "No meta-jargon."),
 (True,  "No skill jargon in final module files."),
 (True,  "Final module files show improvement: hardcoded path removed, off-by-one fixed, some validation added — artifact quality is good (v4 also produces good output, just via a different process)."),
],

}

for (ev, cfg), verdicts in VERDICTS.items():
    meta = json.loads((ROOT / ev / "eval_metadata.json").read_text())
    texts = meta["expectations"]
    assert len(texts) == len(verdicts), f"{ev}/{cfg}: {len(texts)} texts vs {len(verdicts)} verdicts"
    exps = [{"text": t, "passed": bool(p), "evidence": e} for t, (p, e) in zip(texts, verdicts)]
    passed = sum(1 for x in exps if x["passed"])
    total = len(exps)
    grading = {
        "expectations": exps,
        "summary": {"passed": passed, "failed": total - passed, "total": total, "pass_rate": round(passed / total, 4)},
    }
    out = ROOT / ev / cfg / "run-1" / "grading.json"
    out.write_text(json.dumps(grading, indent=2) + "\n")
    print(f"{ev}/{cfg}: {passed}/{total} = {passed/total:.0%}")
